---
title: "Falciparum Genetic Connectedness in the DRC"
author: "Nicholas F. Brazeau"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    highlight: textmate
    theme: lumen
    toc: yes
    toc_float: yes
    toc_depth: 3
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, eval = T, results = 'hide',
                      fig.align = 'center', fig.width = 6, fig.height = 6)
knitr::opts_knit$set(root.dir = here::here(""))

```

```{r, child = 'ind_reports/01-Sample_Clsts_Descriptive.Rmd'}
```

```{r, child = 'ind_reports/02-Genetic_Summaries.Rmd'}
```

```{r, child = 'ind_reports/03-IBD_S_distance_decay.Rmd'}
```

```{r, child = 'ind_reports/04-DISC.Rmd'}
```

```{r, child = 'ind_reports/05-spatial_geo_DISC.Rmd'}
```

```{r, child = 'ind_reports/06-IBD_meioticsibs.Rmd'}
```

```{r, child = 'ind_reports/999-SNP_autocorr.Rmd'}
```

```{r, child = 'ind_reports/999-SpaceCorr.Rmd'}
```

```{r, child = 'ind_reports/999-within_household.Rmd'}
```
