---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Genetic Loci Descriptive Statistics 

```{r, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, eval = T, results = 'hide',
                      fig.align = 'center', fig.width = 8, fig.height = 8)
knitr::opts_knit$set(root.dir = here::here())
```


```{r}
source("R/basics.R")
source("R/pairwise_helpers.R")
library(tidyverse)
#....................................................................................
# Import Genetic Data
#....................................................................................
ibD <- readRDS("data/derived_data/bigbarcode_genetic_data/mipanalyzer.DRCibD.long.mtdt.rds")
ibS <- readRDS("data/derived_data/bigbarcode_genetic_data/mipanalyzer.DRCibS.long.mtdt.rds")
vcf.DRC <- vcfR::read.vcfR("data/derived_data/bigbarcode_genetic_data/mipbivcfR.DRC.vcf")
CHROMPOS <- tibble::tibble(CHROM = vcfR::getCHROM(vcf.DRC),
                           POS = vcfR::getPOS(vcf.DRC))
```

## Overview of Loci Genetic Information
### Number of sites 

```{r, results='asis'}
CHROMPOS.num <- CHROMPOS %>% 
  dplyr::group_by(CHROM) %>% 
  dplyr::summarise(n = n())

DT::datatable(CHROMPOS.num, extensions='Buttons',
               options = list(
              searching = T,
              pageLength = 14,
              dom = 'Bfrtip', 
              buttons = c('csv')))

```

## Pairwise Genetics Comparions
Let's look at pairwise comparison of the identity by state and identity by descent of all of our samples. 
### Pairwise IBS
```{r}
#.....................
# EDA of Our Genetic Data
# for IBS
#.....................
# Pairwise Comparisons -- want full matrix
ibS.exp.hv001 <- expand_distance_matrix(ibS)

pairwiseibS.plotObj <- ibS.exp.hv001 %>%
  dplyr::mutate(smpl1 = forcats::fct_rev(forcats::fct_reorder(.f = smpl1, .x = adm1name.x, .fun = length)),
                smpl2 = forcats::fct_rev(forcats::fct_reorder(.f = smpl2, .x = adm1name.y, .fun = length))) %>%
  ggplot() +
  geom_tile(aes(x=smpl1, y=smpl2, fill = hammings)) +
  ggtitle("Pairwise Identity by State") +
  scale_fill_viridis_c("Ihat") +
  theme_minimal() +
  theme(
    plot.title = element_text(vjust = 0.5, hjust = 0.5, size = 11, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    legend.position = "right",
    legend.text = element_text(hjust = 0.5, vjust = 0.5, size = 8),
    plot.background = element_blank(),
    panel.grid = element_blank()
  )

jpgsnapshot(outpath = "results/figures/pairwiseibS_plot.jpg", plot = pairwiseibS.plotObj)

```

```{r, results='asis', fig.width=11, fig.height=8, fig.align='center'}
plot(pairwiseibS.plotObj)
```

###### Sample
```{r, results='asis'}
ibS.exp.hv001 %>% # selfs already excluded
  summ_var(df = ., x = "hammings", groupingvar = "smpl1") %>% 
  pretty_DT_tab(.)

```

##### Cluster
```{r, results='asis'}
ibS.exp.hv001 %>% # selfs already excluded
  dplyr::group_by(hv001.x) %>% 
  summ_var(df = ., x = "hammings", groupingvar = "hv001.x") %>% 
  pretty_DT_tab(.)
```

##### Prov
```{r, results='asis'}
ibS.exp.hv001 %>% # selfs already excluded
  summ_var(df = ., x = "hammings", groupingvar = "adm1name.x") %>% 
  pretty_DT_tab(.)

```


### Pairwise IBD
```{r}
#.....................
# EDA of Our Genetic Data
# for IBD
#.....................
# Pairwise Comparisons
ibD.exp.hv001 <- expand_distance_matrix(ibD)

pairwiseibD.plotObj <- ibD.exp.hv001 %>%
  dplyr::mutate(smpl1 = forcats::fct_rev(forcats::fct_reorder(.f = smpl1, .x = adm1name.x, .fun = length)),
                smpl2 = forcats::fct_rev(forcats::fct_reorder(.f = smpl2, .x = adm1name.y, .fun = length))) %>%
  ggplot() +
  geom_tile(aes(x=smpl1, y=smpl2, fill = malecotf)) +
  ggtitle("Pairwise Identity by Descent") +
  scale_fill_viridis_c("Ihat") +
  theme_minimal() +
  theme(
    plot.title = element_text(vjust = 0.5, hjust = 0.5, size = 11, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    legend.position = "right",
    legend.text = element_text(hjust = 0.5, vjust = 0.5, size = 8),
    plot.background = element_blank(),
    panel.grid = element_blank()
  )

jpeg("results/figures/pairwiseibD_plot.jpg",
     unit = "in", height = 8, width = 11, res = 500)
plot(pairwiseibD.plotObj)
graphics.off()

```

```{r, results='asis', fig.width=11, fig.height=8, fig.align='center'}
plot(pairwiseibD.plotObj)
```



###### Sample
```{r, results='asis'}
ibS.exp.hv001 %>% # selfs already excluded
  summ_var(df = ., x = "malecotf", groupingvar = "smpl1") %>% 
  pretty_DT_tab(.)
  
```


##### Cluster
```{r, results='asis'}
ibD.exp.hv001 %>% # selfs already excluded
  summ_var(df = ., x = "malecotf", groupingvar = "hv001.x") %>% 
  pretty_DT_tab(.)

```

##### Prov
```{r, results='asis'}
ibD.exp.hv001 %>% # selfs already excluded
  summ_var(df = ., x = "malecotf", groupingvar = "adm1name.x") %>% 
  pretty_DT_tab(.)
```
