---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Inbreeding Gradient Descent Overview
```{r, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, eval = T, results = 'hide',
                      fig.align = 'center', fig.width = 8, fig.height = 8)
knitr::opts_knit$set(root.dir = here::here())
```

```{r}
library(tidyverse)
library(cowplot)
source("R/themes.R")
```

```{r}
#......................
# read results
#......................
all_disc <- readRDS("results/clust_inbd_results/all_smpls/min_cost_inbreedingresults/min_cost_inbreedingresults.RDS")
coi_1_disc <-readRDS("results/clust_inbd_results/smpls_coione/min_cost_inbreedingresults/min_cost_inbreedingresults.RDS")
```

## Visualize Cost
### All Samples 
```{r, results='asis'}
p1 <- all_disc %>% 
  tidyr::unnest(cols = "cost") %>% 
  dplyr::group_by(spacetype) %>% 
  dplyr::mutate(iteration = 1:dplyr::n(),
                spacetype = factor(spacetype, levels = c("gcdist", "roaddist", "airdist"),
                                   labels = c("GC Dist.", "Road Dist.", "Airport Dist."))) %>% 
  ggplot() + 
  geom_point(aes(x = iteration, y = cost)) +
  facet_wrap(~spacetype, scales = "free") + 
  xlab("Iteration") + 
  ylab("Cost") +
  plot_theme + 
   theme(panel.grid = element_line(color = "#bdbdbd", size = 0.1),
         axis.text.x = element_text(family = "Helvetica", hjust = 1, size = 8, angle = 45))

p2 <- all_disc %>% 
  tidyr::unnest(cols = "cost") %>% 
  dplyr::group_by(spacetype) %>% 
  dplyr::mutate(iteration = 1:dplyr::n(),
                spacetype = factor(spacetype, levels = c("gcdist", "roaddist", "airdist"),
                                   labels = c("GC Dist.", "Road Dist.", "Airport Dist."))) %>% 
  dplyr::filter(iteration != 1) %>% 
  ggplot() + 
  geom_point(aes(x = iteration, y = cost)) +
  facet_wrap(~spacetype, scales = "free") + 
  xlab("Iteration") + 
  ylab("Cost") +
  plot_theme + 
   theme(panel.grid = element_line(color = "#bdbdbd", size = 0.1),
         axis.text.x = element_text(family = "Helvetica", hjust = 1, size = 8, angle = 45))
  
p3 <- all_disc %>% 
  tidyr::unnest(cols = "cost") %>% 
  dplyr::group_by(spacetype) %>% 
  dplyr::mutate(iteration = 1:dplyr::n(),
                spacetype = factor(spacetype, levels = c("gcdist", "roaddist", "airdist"),
                                   labels = c("GC Dist.", "Road Dist.", "Airport Dist."))) %>% 
  dplyr::filter(iteration %in% 2000:4000) %>% 
  ggplot() + 
  geom_point(aes(x = iteration, y = cost)) +
  facet_wrap(~spacetype, scales = "free") + 
  xlab("Iteration") + 
  ylab("Cost") +
  plot_theme + 
  theme(panel.grid = element_line(color = "#bdbdbd", size = 0.1),
        axis.text.x = element_text(family = "Helvetica", hjust = 1, size = 8, angle = 45))

p4 <- all_disc %>% 
  tidyr::unnest(cols = "cost") %>% 
  dplyr::group_by(spacetype) %>% 
  dplyr::mutate(iteration = 1:dplyr::n(),
                spacetype = factor(spacetype, levels = c("gcdist", "roaddist", "airdist"),
                                   labels = c("GC Dist.", "Road Dist.", "Airport Dist."))) %>% 
  dplyr::filter(iteration %in% 4e4:5e4) %>% 
  ggplot() + 
  geom_point(aes(x = iteration, y = cost)) +
  facet_wrap(~spacetype, scales = "free") + 
  xlab("Iteration") + 
  ylab("Cost") +
  plot_theme + 
   theme(panel.grid = element_line(color = "#bdbdbd", size = 0.1),
         axis.text.x = element_text(family = "Helvetica", hjust = 1, size = 8, angle = 45))
  

cowplot::plot_grid(p1, p2, p3, p4, nrow = 4, align = "v")

```

**N.B. not quite monotonically decreasing, as the learning rate could potentially be slightly smaller or better mixed between the Fs and the Ms... but it appears to be converged.** 

### Monoclonal Samples 
```{r, results='asis'}
p1 <- coi_1_disc %>% 
  tidyr::unnest(cols = "cost") %>% 
  dplyr::group_by(spacetype) %>% 
  dplyr::mutate(iteration = 1:dplyr::n(),
                spacetype = factor(spacetype, levels = c("gcdist", "roaddist", "airdist"),
                                   labels = c("GC Dist.", "Road Dist.", "Airport Dist."))) %>% 
  ggplot() + 
  geom_point(aes(x = iteration, y = cost)) +
  facet_wrap(~spacetype, scales = "free") + 
  xlab("Iteration") + 
  ylab("Cost") +
  plot_theme + 
  theme(panel.grid = element_line(color = "#bdbdbd", size = 0.1),
        axis.text.x = element_text(family = "Helvetica", hjust = 1, size = 8, angle = 45))

p2 <- coi_1_disc %>% 
  tidyr::unnest(cols = "cost") %>% 
  dplyr::group_by(spacetype) %>% 
  dplyr::mutate(iteration = 1:dplyr::n(),
                spacetype = factor(spacetype, levels = c("gcdist", "roaddist", "airdist"),
                                   labels = c("GC Dist.", "Road Dist.", "Airport Dist."))) %>% 
  dplyr::filter(iteration != 1) %>% 
  ggplot() + 
  geom_point(aes(x = iteration, y = cost)) +
  facet_wrap(~spacetype, scales = "free") + 
  xlab("Iteration") + 
  ylab("Cost") +
  plot_theme + 
  theme(panel.grid = element_line(color = "#bdbdbd", size = 0.1),
        axis.text.x = element_text(family = "Helvetica", hjust = 1, size = 8, angle = 45))

p3 <- coi_1_disc %>% 
  tidyr::unnest(cols = "cost") %>% 
  dplyr::group_by(spacetype) %>% 
  dplyr::mutate(iteration = 1:dplyr::n(),
                spacetype = factor(spacetype, levels = c("gcdist", "roaddist", "airdist"),
                                   labels = c("GC Dist.", "Road Dist.", "Airport Dist."))) %>% 
  dplyr::filter(iteration %in% 2000:4000) %>% 
  ggplot() + 
  geom_point(aes(x = iteration, y = cost)) +
  facet_wrap(~spacetype, scales = "free") + 
  xlab("Iteration") + 
  ylab("Cost") +
  plot_theme + 
  theme(panel.grid = element_line(color = "#bdbdbd", size = 0.1),
        axis.text.x = element_text(family = "Helvetica", hjust = 1, size = 8, angle = 45))


p4 <- coi_1_disc %>% 
  tidyr::unnest(cols = "cost") %>% 
  dplyr::group_by(spacetype) %>% 
  dplyr::mutate(iteration = 1:dplyr::n(),
                spacetype = factor(spacetype, levels = c("gcdist", "roaddist", "airdist"),
                                   labels = c("GC Dist.", "Road Dist.", "Airport Dist."))) %>% 
  dplyr::filter(iteration %in% 4e4:5e4) %>% 
  ggplot() + 
  geom_point(aes(x = iteration, y = cost)) +
  facet_wrap(~spacetype, scales = "free") + 
  xlab("Iteration") + 
  ylab("Cost") +
  plot_theme + 
  theme(panel.grid = element_line(color = "#bdbdbd", size = 0.1),
        axis.text.x = element_text(family = "Helvetica", hjust = 1, size = 8, angle = 45))


cowplot::plot_grid(p1, p2, p3, p4, nrow = 4, align = "v")

```
