---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Inbreeding Gradient Descent
```{r, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, eval = T, results = 'hide',
                      fig.align = 'center', fig.width = 8, fig.height = 8)
knitr::opts_knit$set(root.dir = here::here())
```

```{r}
library(tidyverse)
library(raster)
library(cowplot)
source("R/themes.R")
source("R/basics.R")
# load pretty map aesthetics 
DRCprov <- sf::st_as_sf(readRDS("data/map_bases/gadm/gadm36_COD_1_sp.rds"))
load("data/map_bases/space_mips_maps_bases.rda")
drccites <- readr::read_csv("data/map_bases/DRC_city_coordinates.csv") %>%
  dplyr::filter(population > 350000)

```

```{r}
#...................... 
# point
#......................
clst_inbd_point_plots <- readRDS(file = "results/final_clstb_maps/point_clst_inbd_plots.RDS")
jpeg("results/figures/clust_inbd_results_alldistances_point_plot.jpg", width = 8, height = 8, units = "in", res = 800)
clust_inbd_result_point_plotObj <- cowplot::plot_grid(clst_inbd_point_plots[[1]], clst_inbd_point_plots[[2]],
                                                      clst_inbd_point_plots[[3]], clst_inbd_point_plots[[4]],
                                                      nrow = 2,
                                                      labels = c("(A)", "(B)", "(C)", "(D)"))
graphics.off()

#...................... 
# raster
#......................
clst_inbd_plots_rstr <- readRDS(file = "results/final_clstb_maps/raster_clst_inbd_plots.RDS")
clust_inbd_result_rstr_plotObj <- cowplot::plot_grid(clst_inbd_plots_rstr[[1]], clst_inbd_plots_rstr[[2]],
                                                     clst_inbd_plots_rstr[[3]], clst_inbd_plots_rstr[[4]],
                                                     nrow = 2,
                                                     labels = c("(A)", "(B)", "(C)", "(D)"))

jpeg("results/figures/clust_inbd_results_alldistances_rstr_plot.jpg", width = 8, height = 8, units = "in", res = 800)
plot(clust_inbd_result_rstr_plotObj)
graphics.off()
```
```{r, results='asis'}
plot(clust_inbd_result_point_plotObj)
```

```{r, results='asis'}
plot(clust_inbd_result_rstr_plotObj)
```

```{r}
# read in urban and prevalence data 
urban <- raster::raster("~/Documents/GitHub/Space_the_Final_Miptier/data/derived_data/urbanicity_raster/urbanicity.grd")
parasiterate <- raster::raster("~/Documents/GitHub/Space_the_Final_Miptier/data/derived_data/MAPrasters/pfincidence.grd")



urban_rstr_plotObj <-  ggplot() + 
  ggspatial::layer_spatial(data = urban, aes(fill = stat(band1))) +
  scale_fill_distiller("Urbanicity", type = "div", palette = "RdYlBu", na.value = NA) +
  geom_sf(data = DRCprov, color = "#737373", fill = NA, size = 0.05) +
  prettybasemap_nodrc_nonorth_dark +
    geom_point(data = drccites, aes(x = longnum, y=latnum), alpha = 0.5) +
    geom_text(data = drccites, aes(label = city, x = longnum, y=latnum),
              hjust = 0.5, vjust = 0.5, nudge_y = 0.25, fontface = "bold",
              size = 3,
              alpha = 0.8)

incid_rstr_plotObj <- ggplot() +
  ggspatial::layer_spatial(data = parasiterate, aes(fill = stat(band1))) +
  scale_fill_distiller("MAP \n Incidence", type = "div", palette = "RdYlBu", na.value = NA) +
  geom_sf(data = DRCprov, color = "#737373", fill = NA, size = 0.05) +
  prettybasemap_nodrc_nonorth_dark +
    geom_point(data = drccites, aes(x = longnum, y=latnum), alpha = 0.5) +
    geom_text(data = drccites, aes(label = city, x = longnum, y=latnum),
              hjust = 0.5, vjust = 0.5, nudge_y = 0.25, fontface = "bold",
              size = 3,
              alpha = 0.8)

# make plot
clust_inbd_results_gc <- cowplot::plot_grid(clst_inbd_plots_rstr[[2]], urban_rstr_plotObj, incid_rstr_plotObj,
                                            labels = c("(A)", "(B)", "(C)"), ncol = 1, align = "v")
jpgsnapshot(outpath = "results/figures/GC_clust_inbd_resultsincidence_urban_raster_combined.jpg",
            plot = clust_inbd_results_gc)

clust_inbd_results_road <- cowplot::plot_grid(clst_inbd_plots_rstr[[4]], urban_rstr_plotObj, incid_rstr_plotObj,
                                              labels = c("(A)", "(B)", "(C)"), ncol = 1, align = "v")
jpgsnapshot(outpath = "results/figures/Rooad_clust_inbd_resultsincidence_urban_raster_combined.jpg",
            plot = clust_inbd_results_road)

```

## Greater Circle, Ubranicity, Incidence

```{r, results='asis', height = 11, width = 8}
plot(clust_inbd_results_gc)
```

## Road Distance, Ubranicity, Incidence
```{r, results='asis', height = 11, width = 8}
plot(clust_inbd_results_road)
```
