---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Inbreeding Gradient Descent
```{r, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, eval = T, results = 'hide',
                      fig.align = 'center', fig.width = 8, fig.height = 8)
knitr::opts_knit$set(root.dir = here::here())
```

```{r}
library(tidyverse)
library(raster)
library(cowplot)
library(PrevMap)
source("R/themes.R")
source("R/basics.R")
# load pretty map aesthetics 
DRCprov <- sf::st_as_sf(readRDS("data/map_bases/gadm/gadm36_COD_1_sp.rds"))
load("data/map_bases/space_mips_maps_bases.rda")
drccites <- readr::read_csv("data/map_bases/DRC_city_coordinates.csv") %>%
  dplyr::filter(population > 350000)

```
```{r}
urbanrstr <- raster::raster("data/derived_data/urbanicity_raster/urbanicity.grd")
ggplot() +
  ggspatial::layer_spatial(data = urbanrstr, aes(fill = stat(band1))) +
  geom_sf(data = DRCprov, color = "#737373", fill = NA, size = 0.05) +
  #prettybasemap_nodrc_dark +
  # scale_fill_distiller("Urbanicity", type = "div", palette = "RdYlBu", 
  #                      na.value = NA, limits = c(-5, 6)) +
  scale_fill_distiller("Urbanicity", type = "div", palette = "RdYlBu",
                       na.value = NA) +
  geom_point(data = drccites, 
             aes(x = longnum, y=latnum)) +
  ggrepel::geom_text_repel(data = drccites, aes(label = city, x = longnum, y=latnum), 
                           hjust = 0.5, vjust = 0.5, nudge_y = 0.3, 
                           fontface = "bold", color = "#bdbdbd") 

```
```{r}
pfincidence <- raster::raster("data/raw_data/MAPrasters/getRaster/2019_Global_Pf_Incidence.201310_.18_40_8_2020_09_18.tiff")
pfincidence <- raster::mask(pfincidence, DRCprov)
ggplot() +
  ggspatial::layer_spatial(data = pfincidence, aes(fill = stat(band1))) +
  geom_sf(data = DRCprov, color = "#737373", fill = NA, size = 0.05) +
  #prettybasemap_nodrc_dark +
  scale_fill_distiller("Pf Incidence", type = "div", palette = "RdYlBu", na.value = NA) +
  geom_point(data = drccites, 
             aes(x = longnum, y=latnum)) +
  ggrepel::geom_text_repel(data = drccites, aes(label = city, x = longnum, y=latnum), 
                           hjust = 0.5, vjust = 0.5, nudge_y = 0.3, 
                           fontface = "bold", color = "#bdbdbd") 

```
