---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Spatial Random Forest
Here, I will use random forest to model both the spatial autocorrelation and the relationship of IBD-Centrality with various _a priori_ risk factor covariates. 
```{r}
library(tidyverse)
library(raster)
library(ranger)
source("~/Documents/GitHub/Space_the_Final_Miptier/R/basics.R")
source("~/Documents/GitHub/Space_the_Final_Miptier/R/themes.R")
source("~/Documents/GitHub/Space_the_Final_Miptier/R/pairwise_helpers.R")
```

```{r}
drcsmpls <- readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/distance_data/drcsmpls_foruse.rds") %>%
  magrittr::set_colnames(tolower(colnames(.))) %>%
  dplyr::select(c("id", "hv001")) %>% 
  dplyr::rename(name = id)

mtdt <- readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/derived_data/sample_metadata.rds") %>% 
  magrittr::set_colnames(tolower(colnames(.))) %>%
  dplyr::rename(name = id) %>% 
  dplyr::select(c("name", "hv001", "adm1name", "longnum", "latnum")) %>% 
  dplyr::filter(name %in% drcsmpls$name)

# map bases
DRCprov <- sf::st_as_sf(readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/map_bases/gadm/gadm36_COD_1_sp.rds"))
load("~/Documents/GitHub/Space_the_Final_Miptier/data/map_bases/space_mips_maps_bases.rda")

# drc cities
drccites <- readxl::read_excel("~/Documents/GitHub/Space_the_Final_Miptier/data/map_bases/DRC_city_coordinates.xlsx") %>% 
  dplyr::mutate(latnum = as.numeric( stringr::str_split_fixed(coordinates, ",", n=2)[,1] ),
                longnum = as.numeric( stringr::str_split_fixed(coordinates, ",", n=2)[,2] ) 
                )

# dhs coord points
ge <- sf::st_as_sf(readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/raw_data/dhsdata/datasets/CDGE61FL.rds")) %>% 
  magrittr::set_colnames(tolower(colnames(.))) %>% 
  dplyr::rename(hv001 = dhsclust) 

```

```{r}
# ibd
ibD <- readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/derived_data/bigbarcode_genetic_data/mipanalyzer.DRCibD_polarized_biallelic_processed.long.rds")

# log2 IBD measure
ibD <- ibD %>% 
  dplyr::mutate(malecotf_gens = -log2(malecotf),
                malecotf_gens_inv = 1/malecotf_gens)

# bring in centrality
cent <- readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/derived_data/centrality_measures/centrality_final_wi_and_knn5.RDS")

```

```{r}
#..............................................................
# First need buffer distances for the X_G covariate
#..............................................................
spatmat <- readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/distance_data/distancematrix_bycluster.rds") 
spatmat <- expand_distance_matrix(spatmat)

# need to expand out spatmat to 
# account for repeat obs within clusters
# and need a self category
# NB, need self category so that the columns are stable/consistent 
# (otherwise hv001 dist would be moving)

rptclsts <- cent %>% 
  dplyr::select("name", "hv001") %>% 
  dplyr::mutate(uniid = paste0(tolower(name), "_", hv001))

rptclsts <- tibble::as_tibble( t(combn(rptclsts$uniid, 2)) ) %>% 
  dplyr::mutate(
    smpl1 = toupper( stringr::str_split_fixed(V1, "_", n=2)[,1] ),
    smpl2 = toupper( stringr::str_split_fixed(V2, "_", n=2)[,1] ),
    hv001.x = as.numeric( stringr::str_split_fixed(V1, "_", n=2)[,2] ),
    hv001.y = as.numeric( stringr::str_split_fixed(V2, "_", n=2)[,2] )
  )

rptclsts.self <- unique(c(rptclsts$V1, rptclsts$V2))

# pull in hv001 for selves
smpllong <- mtdt %>% 
  dplyr::select(c("name", "hv001")) %>% 
  dplyr::mutate(V1 = paste0(tolower(name), "_", hv001),
                hv001.y = hv001) %>% 
  dplyr::rename(hv001.x = hv001) %>% 
  dplyr::select(c("V1", "hv001.x", "hv001.y"))

rptclsts.self <- tibble::tibble(
  V1 = rptclsts.self,
  V2 = rptclsts.self,
  smpl1 = "",
  smpl2 = "" ) %>% 
  dplyr::left_join(x = ., y = smpllong, 
                                  by = "V1") %>% 
  dplyr::filter(!duplicated(.))
  
# bind self and others
rptclsts <- rbind.data.frame(rptclsts, rptclsts.self)

rptclsts <- dplyr::left_join(rptclsts, spatmat, by = c("hv001.x", "hv001.y")) %>% 
  dplyr::mutate(
     gcdistance = ifelse(hv001.x == hv001.y, .Machine$double.xmin, gcdistance),
     roaddistance = ifelse(hv001.x == hv001.y, .Machine$double.xmin, roaddistance),
     riverdist = ifelse(hv001.x == hv001.y, .Machine$double.xmin, riverdist),
    
     # make km and then log transform  
     gcdistance = log((gcdistance/1e3)),
     roaddistance = log((roaddistance/1e3)),
     riverdist = log((riverdist/1e3))
     
  )

# expand this out
rptclsts <- rptclsts %>% 
  dplyr::select(-c("smpl1", "smpl2", "hv001.x", "hv001.y")) %>% 
  expand_distance_matrix(.) %>% 
  dplyr::filter(!duplicated(.)) %>%  # self got put twice
  dplyr::arrange(V1, V2) %>% 
  dplyr::select(-c("V2")) %>% 
  dplyr::rename(uni_id = V1) 

#..............................................................
# Finally now have a full distance matrix in long format
# including 0s for along the diagonal
#..............................................................

# now take this into tidyverse
spatmat.dat <- rptclsts %>% 
  tidyr::gather(., key = "distcat", value = "dist", 2:4) %>% 
  dplyr::group_by(distcat) %>% 
  tidyr::nest()
  

spatmat.dat <- spatmat.dat %>% 
  dplyr::mutate(spacecovar = purrr::map(data, function(x){
    clst.list <- split(x$dist, factor(x$uni_id)) # get all other pairwise dist for each unique point
    clstcols <- do.call("rbind.data.frame", clst.list)
    colnames(clstcols) <- paste0("d", 1:ncol(clstcols))
    return(clstcols)
  }))

spacecovars <- colnames(spatmat.dat$spacecovar[[1]])

```

## Spatial Random Forest
### Modeling IBD-Centrality as a Function of Geographic Space

```{r}
# overwrite data col
spatmat.dat$data <- purrr::map(spatmat.dat$spacecovar, function(x){
  ret <- cbind.data.frame(cent, x)
  return(ret)
})

# run ranger model
wrap_ranger_dij <- function(outcome, ntree, data){
  dij <- colnames(spatmat.dat$data[[1]])
  dij <- dij[ grepl("d[0-9]", dij) ]
  eq <- as.formula(paste(outcome, " ~ ", paste(dij, collapse = "+")))
  
  ret <- ranger(eq, data, importance="impurity",
                quantreg=TRUE, 
                num.trees=ntree, 
                seed=1)
  
}

spatmat.dat$rangerdij_wi <- purrr::map(spatmat.dat$data, wrap_ranger_dij, ntree = 150, outcome = "centrality_pr_wi_scaled")

spatmat.dat$rangerdij_knn5 <- purrr::map(spatmat.dat$data, wrap_ranger_dij, ntree = 150, outcome = "centrality_pr_knn5")




```

```{r, results='asis'}
spatmat.dat$rangerdij_wi
spatmat.dat$rangerdij_knn5
```

### Modeling IBD-Centrality as a Function of Geographic Space and Covars
```{r}
# overwrite data col
covarmat <- readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/derived_data/covar_rasterstack_samplinglocations_raw.RDS")
betas <- colnames(covarmat)[colnames(covarmat) != "hv001"]

cent.covar <- dplyr::left_join(cent, covarmat, by = "hv001")

spatmat.dat$data <- purrr::map(spatmat.dat$spacecovar, function(x){
  ret <- cbind.data.frame(cent.covar, x)
  return(ret)
})

# run ranger model
wrap_ranger_dij_covar <- function(outcome, ntree, data){
  dij <- colnames(spatmat.dat$data[[1]])
  dij <- dij[ grepl("d[0-9]", dij) ]
  eq <- as.formula(paste(outcome, " ~ ", 
                         paste(betas, collapse = "+"), "+", 
                         paste(dij, collapse = "+")))
  
  ret <- ranger(eq, data, importance="impurity",
                quantreg=TRUE, 
                num.trees=ntree, 
                seed=1)
  
}

spatmat.dat$rangerdij_wi <- purrr::map(spatmat.dat$data, 
                                       wrap_ranger_dij_covar, 
                                       ntree = 150, 
                                       outcome = "centrality_pr_wi_scaled")

spatmat.dat$rangerdij_knn5 <- purrr::map(spatmat.dat$data, 
                                         wrap_ranger_dij_covar, 
                                         ntree = 150, 
                                         outcome = "centrality_pr_knn5")

```

```{r, results='asis'}
spatmat.dat$rangerdij_wi
spatmat.dat$rangerdij_knn5
```

## PrevMap Comparison
```{r}


```

