#.............
# Net Use
#.............

#.............
# ACT Use
#.............

#.............
# Distance Hospital
#.............

#.............
# Urbanicity
#.............

#.............
# Precipitation
#.............


#.............
# Cluster-Level Altitude
#.............
dt <- dt %>%
  dplyr::mutate(alt_dem_cont_clst = ifelse(alt_dem == 9999, NA, alt_dem), # note no missing (likely dropped with missing gps)
                alt_dem_cont_scale_clst = my.scale(alt_dem_cont_clst, center = T, scale = T)
  )
