---
output: html_document
editor_options: 
  chunk_output_type: console
---

# TODO 
add airports, add urbanicity and prevalence

```{r}
library(tidyverse)
```

```{r}

#..............................................................
# import for plotting
#..............................................................
drcsmpls <- readRDS("data/derived_data/sample_metadata.rds") %>% 
  dplyr::select(c("barcode", "hv001"))
ge <- readRDS("data/derived_data/spacemips_GE.rds")
load("data/map_bases/space_mips_maps_bases.rda")
```


```{r, results='asis'}
roadnetworkplotObj <- readRDS("data/distance_data/roadnetworkplotObj.RDS")
rivernetworkplotObj <- readRDS("data/distance_data/rivernetworkplotObj.RDS")


cowplot::plot_grid(smplocations, roadnetworkplotObj, rivernetworkplotObj,
                   nrow = 1, align = "h")
```

```{r}

smplocations.nolegend <- ggplot() +
  geom_sf(data = DRCprov, color = "#737373", fill = "#525252", size = 0.05) +
  prettybasemap_nodrc_dark +
  geom_point(data = ge.plotpts, 
              aes(x = longnum, y = latnum, size = n, color = factor(smpls), shape = factor(smpls)), 
              alpha = 0.8) +
  scale_color_manual("DHS \n Cluster", values = c("#a6bddb", "#ef3b2c")) +
  scale_size("Cluster \n Size", range = c(1, 4)) +
  theme(
    legend.position = "none",
    legend.title = element_text(face = "bold", size = 12, vjust = 0.5, hjust = 0.5),
    legend.text = element_text(face = "bold", size = 11)
  ) 

jpeg("results/figures/smplocationsroad_river_clster.jpg",
     width = 11, height = 8, units = "in", res = 300)
cowplot::plot_grid(smplocations.nolegend, roadnetworkplotObj, rivernetworkplotObj,
                   nrow = 1, align = "h", labels = c("(A)", "(B)", "(C)"))
graphics.off()

```
