---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Genetic Pairwise Summaries
Let's look at pairwise comparison of the identity by state and identity by descent of all of our samples. We will look at them with respect to Province just for some sembalance of "space". 
```{r, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, eval = T, results = 'hide',
                      fig.align = 'center', fig.width = 8, fig.height = 8)
```


```{r}
source("~/Documents/GitHub/Space_the_Final_Miptier/R/pairwise_helpers.R")
library(tidyverse)

drcsmpls <- readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/distance_data/drcsmpls_foruse.rds") %>%
  magrittr::set_colnames(tolower(colnames(.))) %>%
  dplyr::select(c("id", "hv001")) %>% 
  dplyr::rename(name = id)

mtdt <- readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/derived_data/sample_metadata.rds") %>% 
  magrittr::set_colnames(tolower(colnames(.))) %>%
  dplyr::rename(name = id) %>% 
  dplyr::select(c("name", "country", "hv001", "adm1name", "longnum", "latnum")) %>% 
  dplyr::filter(name %in% drcsmpls$name)

# drc prov for plot
DRCprov <- sf::st_as_sf(readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/map_bases/gadm/gadm36_COD_1_sp.rds"))

#....................................................................................
# Import Genetic Data
#....................................................................................
ibD <- readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/derived_data/bigbarcode_genetic_data/mipanalyzer.DRCibD_polarized_biallelic_processed.long.rds")
ibS <- readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/derived_data/bigbarcode_genetic_data/mipanalyzer.DRCibS_polarized_biallelic_processed.long.rds")

ge <- readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/derived_data/spacemips_GE.rds")

```

<!-- TO DO this should all be once call -- or import -->

## Pairwise IBS
```{r}
#.....................
# EDA of Our Genetic Data
# for IBS
#.....................
# Pairwise Comparisons
ibS.exp <- expand_distance_matrix(ibS)

ge.names <- ge %>% 
  dplyr::left_join(drcsmpls, ., by = "hv001") %>% 
  dplyr::select(-c("geometry")) %>% 
  dplyr::rename(smpl1 = name) 

ibS.exp.hv001 <- left_join(x=ibS.exp, y = ge.names, by = "smpl1")

ge.names <- ge.names %>% 
  dplyr::rename(smpl2 = smpl1)

ibS.exp.hv001 <- left_join(x=ibS.exp.hv001, y = ge.names, by = "smpl2")



pairwiseibS.plotObj <- ibS.exp.hv001 %>%
  dplyr::mutate(smpl1 = forcats::fct_rev(forcats::fct_reorder(.f = smpl1, .x = adm1name.x, .fun = length)),
                smpl2 = forcats::fct_rev(forcats::fct_reorder(.f = smpl2, .x = adm1name.y, .fun = length))) %>%
  ggplot() +
  geom_tile(aes(x=smpl1, y=smpl2, fill = hammings)) +
  ggtitle("Pairwise Identity by State") +
  scale_fill_viridis_c("Ihat") +
  theme_minimal() +
  theme(
    plot.title = element_text(vjust = 0.5, hjust = 0.5, size = 11, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    legend.position = "right",
    legend.text = element_text(hjust = 0.5, vjust = 0.5, size = 8),
    plot.background = element_blank(),
    panel.grid = element_blank()
  )

jpeg("~/Documents/GitHub/Space_the_Final_Miptier/results/figures/pairwiseibS_plot.jpg",
     unit = "in", height = 8, width = 11, res = 500)
plot(pairwiseibS.plotObj)
graphics.off()

```

```{r, results='asis', fig.width=11, fig.height=8, fig.align='center'}
plot(pairwiseibS.plotObj)
```


### Pairwise IBS Stats
##### Sample
```{r, results='asis'}
ibS.exp.hv001 %>% # selfs already excluded
  dplyr::group_by(smpl1) %>% 
  dplyr::summarise(
    n = n(),
    minIBS = min(hammings),
    quart25IBS = quantile(hammings, 0.25),
    medIBS = median(hammings),
    meanIBS = mean(hammings),
    sdIBS = sd(hammings),
    quart75IBS = quantile(hammings, 0.75),
    maxIBS = max(hammings)
  ) %>% 
  dplyr::mutate_if(is.numeric, round, 2) %>% 
  DT::datatable(., extensions='Buttons',
                options = list(
                  searching = T,
                  pageLength = 20,
                  dom = 'Bfrtip', 
                  buttons = c('csv')))

```


#### Prov
```{r, results='asis'}
ibS.exp.hv001 %>% # selfs already excluded
  dplyr::group_by(adm1name.x) %>% 
  dplyr::summarise(
    n = n(),
    minIBS = min(hammings),
    quart25IBS = quantile(hammings, 0.25),
    medIBS = median(hammings),
    meanIBS = mean(hammings),
    sdIBS = sd(hammings),
    quart75IBS = quantile(hammings, 0.75),
    maxIBS = max(hammings)
  ) %>% 
  dplyr::mutate_if(is.numeric, round, 2) %>% 
  DT::datatable(., extensions='Buttons',
                options = list(
                  searching = T,
                  pageLength = 20,
                  dom = 'Bfrtip', 
                  buttons = c('csv')))

```


#### Cluster
```{r, results='asis'}
ibS.exp.hv001 %>% # selfs already excluded
  dplyr::group_by(hv001.x) %>% 
  dplyr::summarise(
    n = n(),
    minIBS = min(hammings),
    quart25IBS = quantile(hammings, 0.25),
    medIBS = median(hammings),
    meanIBS = mean(hammings),
    sdIBS = sd(hammings),
    quart75IBS = quantile(hammings, 0.75),
    maxIBS = max(hammings)
  ) %>% 
  dplyr::mutate_if(is.numeric, round, 2) %>% 
  DT::datatable(., extensions='Buttons',
                options = list(
                  searching = T,
                  pageLength = 20,
                  dom = 'Bfrtip', 
                  buttons = c('csv')))

```

## Pairwise IBD
```{r}
#.....................
# EDA of Our Genetic Data
# for IBD
#.....................
# Pairwise Comparisons
ibD.exp <- expand_distance_matrix(ibD)

ge.names <- ge %>% 
  dplyr::left_join(drcsmpls, ., by = "hv001") %>% 
  dplyr::select(-c("geometry")) %>% 
  dplyr::rename(smpl1 = name) 

ibD.exp.hv001 <- left_join(x=ibD.exp, y = ge.names, by = "smpl1")

ge.names <- ge.names %>% 
  dplyr::rename(smpl2 = smpl1)

ibD.exp.hv001 <- left_join(x=ibD.exp.hv001, y = ge.names, by = "smpl2")



pairwiseibD.plotObj <- ibD.exp.hv001 %>%
  dplyr::mutate(smpl1 = forcats::fct_rev(forcats::fct_reorder(.f = smpl1, .x = adm1name.x, .fun = length)),
                smpl2 = forcats::fct_rev(forcats::fct_reorder(.f = smpl2, .x = adm1name.y, .fun = length))) %>%
  ggplot() +
  geom_tile(aes(x=smpl1, y=smpl2, fill = malecotf)) +
  ggtitle("Pairwise Identity by Descent") +
  scale_fill_viridis_c("Ihat") +
  theme_minimal() +
  theme(
    plot.title = element_text(vjust = 0.5, hjust = 0.5, size = 11, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    legend.position = "right",
    legend.text = element_text(hjust = 0.5, vjust = 0.5, size = 8),
    plot.background = element_blank(),
    panel.grid = element_blank()
  )

jpeg("~/Documents/GitHub/Space_the_Final_Miptier/results/figures/pairwiseibD_plot.jpg",
     unit = "in", height = 8, width = 11, res = 500)
plot(pairwiseibD.plotObj)
graphics.off()

```

```{r, results='asis', fig.width=11, fig.height=8, fig.align='center'}
plot(pairwiseibD.plotObj)
```



### Pairwise IBD Stats
#### Prov
```{r, results='asis'}
ibD.exp.hv001 %>% # selfs already excluded
  dplyr::group_by(smpl1) %>% 
  dplyr::summarise(
    n = n(),
    minIBS = min(malecotf),
    quart25IBS = quantile(malecotf, 0.25),
    medIBS = median(malecotf),
    meanIBS = mean(malecotf),
    sdIBS = sd(malecotf),
    quart75IBS = quantile(malecotf, 0.75),
    maxIBS = max(malecotf)
  ) %>% 
  dplyr::mutate_if(is.numeric, round, 2) %>% 
  DT::datatable(., extensions='Buttons',
                options = list(
                  searching = T,
                  pageLength = 20,
                  dom = 'Bfrtip', 
                  buttons = c('csv')))

```




#### Cluster
```{r, results='asis'}
ibD.exp.hv001 %>% # selfs already excluded
  dplyr::group_by(hv001.x) %>% 
  dplyr::summarise(
    n = n(),
    minIBS = min(malecotf),
    quart25IBS = quantile(malecotf, 0.25),
    medIBS = median(malecotf),
    meanIBS = mean(malecotf),
    sdIBS = sd(malecotf),
    quart75IBS = quantile(malecotf, 0.75),
    maxIBS = max(malecotf)
  ) %>% 
  dplyr::mutate_if(is.numeric, round, 2) %>% 
  DT::datatable(., extensions='Buttons',
                options = list(
                  searching = T,
                  pageLength = 20,
                  dom = 'Bfrtip', 
                  buttons = c('csv')))

```

## Sampling Locations
```{r}
drcsmpls.ge <- dplyr::left_join(drcsmpls, ge, by = "hv001")
drcsmpls.ge <- drcsmpls.ge %>% 
  dplyr::group_by(hv001) %>% 
  dplyr::summarise(n = n(),
                   longnum = mean(longnum),
                   latnum = mean(latnum)) # geocoords same w/in clust

drcsmpls.ge$smpls <- "Sampled"
ge.notsmpl <- ge %>% 
  dplyr::select(c("hv001", "longnum", "latnum")) %>% 
  dplyr::filter(!hv001 %in% drcsmpls.ge$hv001) %>% 
  dplyr::mutate(
    n = 0.8, 
    smpls = "Not Sampled"
  )

ge.plotpts <- rbind.data.frame(drcsmpls.ge, ge.notsmpl)

load("~/Documents/GitHub/Space_the_Final_Miptier/data/map_bases/space_mips_maps_bases.rda")
smplocations <- ggplot() +
  geom_sf(data = DRCprov, color = "#737373", fill = "#525252", size = 0.05) +
  prettybasemap_nodrc_dark +
  geom_point(data = ge.plotpts, 
              aes(x = longnum, y = latnum, size = n, color = factor(smpls)), 
              alpha = 0.8, show.legend = F) +
  scale_color_viridis_d("DHS Cluster") +
  scale_size("Cluster Size", range = c(1, 4)) +
  theme(
    legend.position = "left",
    legend.title = element_text(face = "bold", size = 12, vjust = 0.5, hjust = 0.5),
    legend.text = element_text(face = "bold", size = 11)
  ) + 
   guides(fill=guide_legend(ncol=2))

jpeg("~/Documents/GitHub/Space_the_Final_Miptier/results/figures/smplocations_clster.jpg",
     width = 8, height = 8, units = "in", res = 300)
plot(smplocations)
graphics.off()

```
```{r, results='asis'}
plot(smplocations)
```
```{r, results='asis'}
roadnetworkplotObj <- readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/distance_data/roadnetworkplotObj.RDS")
rivernetworkplotObj <- readRDS("~/Documents/GitHub/Space_the_Final_Miptier/data/distance_data/rivernetworkplotObj.RDS")


cowplot::plot_grid(smplocations, roadnetworkplotObj, rivernetworkplotObj,
                   nrow = 1, align = "h")
```

```{r}
jpeg("~/Documents/GitHub/Space_the_Final_Miptier/results/figures/smplocationsroad_river_clster.jpg",
     width = 11, height = 8, units = "in", res = 300)
cowplot::plot_grid(smplocations, roadnetworkplotObj, rivernetworkplotObj,
                   nrow = 1, align = "h", labels = c("(A)", "(B)", "(C)"))
graphics.off()

```
