---
title: "Untitled"
author: "NFB"
date: "9/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#.....................
# Manipulate for Decay Comparisons
#.....................
# merge in cluster informations
colnames(drcsmpls)[1] <- "smpl1"
ibd <- dplyr::left_join(ibd, drcsmpls, by = "smpl1")
ibs <- dplyr::left_join(ibs, drcsmpls, by = "smpl1")

colnames(drcsmpls)[1] <- "smpl2"
ibd <- dplyr::left_join(ibd, drcsmpls, by = "smpl2")
ibs <- dplyr::left_join(ibs, drcsmpls, by = "smpl2")

#.......................................................................
# Import Distance matrix
#....................................................................... 
distancematrix.cluster <- readRDS("data/distance_data/distancematrix_bycluster.rds")


########################################################################## 
########  IBS Cluster Level Manipulate & Summarize           
########################################################################## 
IBSdist <- long_distance_matrix_join(x=ibs, y=distancematrix.cluster[,1:3],
                                     by = c("hv001.x", "hv001.y")) %>%
  dplyr::mutate(gcdistance = gcdistance/1e3)

IBSdist <- long_distance_matrix_join(x=IBSdist, y=distancematrix.cluster[,c(1,2,4)],
                                     by = c("hv001.x", "hv001.y")) %>%
  dplyr::mutate(roaddistance = roaddistance/1e3)

IBSdist$roaddistance[IBSdist$hv001.x == IBSdist$hv001.y] <- 0
IBSdist$gcdistance[IBSdist$hv001.x == IBSdist$hv001.y] <- 0

IBSdist$gcdistance_cat <- cut(x = c(IBSdist$gcdistance),
                              breaks = c(0, 1e-26, 5, 10, 15, 20, 25, 50, 100,
                                         200, 300, 400, 500, 1000, 1500, Inf),
                              right = F, #
                              labels = c("Within", "<5km", "<10km", "<15km",
                                         "<20km", "<25km", "<50km", "<100km",
                                         "<200km", "<300km", "<400km", "<500km",
                                         "<1000km", "<15000km", ">15000km")
                              )


IBSdist$roaddistance_cat <- cut(x = c(IBSdist$roaddistance),
                                breaks = c(0, 1e-26, 5, 10, 15, 20, 25, 50, 100,
                                           200, 300, 400, 500, 1000, 1500, Inf),
                                right = F, #
                                labels = c("Within", "<5km", "<10km", "<15km",
                                           "<20km", "<25km", "<50km", "<100km",
                                           "<200km", "<300km", "<400km", "<500km",
                                           "<1000km", "<15000km", ">15000km")
                                )


IBSdist.gc.summary <- IBSdist %>%
  dplyr::group_by(gcdistance_cat) %>%
  dplyr::summarise(
    n = n(),
    IBSmin = min(hammingibs),
    IBS25 = quantile(hammingibs, c(0.25)),
    IBSmean = mean(hammingibs),
    IBSsd = sd(hammingibs),
    IBSmedian = median(hammingibs),
    IBS75 = quantile(hammingibs, c(0.75)),
    IBSmax = max(hammingibs)
  )

IBSdist.road.summary <- IBSdist %>%
  dplyr::group_by(roaddistance_cat) %>%
  dplyr::summarise(
    n = n(),
    IBSmin = min(hammingibs),
    IBS25 = quantile(hammingibs, c(0.25)),
    IBSmean = mean(hammingibs),
    IBSsd = sd(hammingibs),
    IBSmedian = median(hammingibs),
    IBS75 = quantile(hammingibs, c(0.75)),
    IBSmax = max(hammingibs)
  )



IBSdecay.plot <- IBSdist %>%
  dplyr::select(-c("gcdistance", "roaddistance")) %>%
  tidyr::gather(., key = "distmetric", value = "distcat", 6:7) %>%
  dplyr::mutate(distcat = factor(distcat, levels = c("gcdistance_cat", "roaddistance_cat"), labels = c("GC Dist.", "Road Dist."))) %>%
  ggplot() +
  geom_boxplot(aes(x=distcat, y = hammingibs)) +
  facet_wrap(.~distmetric) +
  theme_ibd +
  theme(axis.text.x = element_text(angle = 90))


```




## IBD Decay
```{r}
#####################################################################################
########         IBD Cluster Level Manipulate & Summarize           #################
#####################################################################################
IBDdist <- long_distance_matrix_join(x=ibd, y=distancematrix.cluster[,1:3],
                                     by = c("hv001.x", "hv001.y")) %>%
  dplyr::mutate(gcdistance = gcdistance/1e3)

IBDdist <- long_distance_matrix_join(x=IBDdist, y=distancematrix.cluster[,c(1,2,4)],
                                     by = c("hv001.x", "hv001.y")) %>%
  dplyr::mutate(roaddistance = roaddistance/1e3)

IBDdist$roaddistance[IBDdist$hv001.x == IBDdist$hv001.y] <- 0
IBDdist$gcdistance[IBDdist$hv001.x == IBDdist$hv001.y] <- 0

IBDdist$gcdistance_cat <- cut(x = c(IBDdist$gcdistance),
                              breaks = c(0, 1e-26, 5, 10, 15, 20, 25, 50, 100,
                                         200, 300, 400, 500, 1000, 1500, Inf),
                              right = F, #
                              labels = c("Within", "<5km", "<10km", "<15km",
                                         "<20km", "<25km", "<50km", "<100km",
                                         "<200km", "<300km", "<400km", "<500km",
                                         "<1000km", "<15000km", ">15000km")
)


IBDdist$roaddistance_cat <- cut(x = c(IBDdist$roaddistance),
                                breaks = c(0, 1e-26, 5, 10, 15, 20, 25, 50, 100,
                                           200, 300, 400, 500, 1000, 1500, Inf),
                                right = F, #
                                labels = c("Within", "<5km", "<10km", "<15km",
                                           "<20km", "<25km", "<50km", "<100km",
                                           "<200km", "<300km", "<400km", "<500km",
                                           "<1000km", "<15000km", ">15000km")
)


IBDdist.gc.summary <- IBDdist %>%
  dplyr::group_by(gcdistance_cat) %>%
  dplyr::summarise(
    n = n(),
    IBDmin = min(malecotf),
    IBD25 = quantile(malecotf, c(0.25)),
    IBDmean = mean(malecotf),
    IBDsd = sd(malecotf),
    IBDmedian = median(malecotf),
    IBD75 = quantile(malecotf, c(0.75)),
    IBDmax = max(malecotf)
  )

IBDdist.road.summary <- IBDdist %>%
  dplyr::group_by(roaddistance_cat) %>%
  dplyr::summarise(
    n = n(),
    IBDmin = min(malecotf),
    IBD25 = quantile(malecotf, c(0.25)),
    IBDmean = mean(malecotf),
    IBDsd = sd(malecotf),
    IBDmedian = median(malecotf),
    IBD75 = quantile(malecotf, c(0.75)),
    IBDmax = max(malecotf)
  )



IBDdecay.plot <- IBDdist %>%
  dplyr::select(-c("gcdistance", "roaddistance")) %>%
  tidyr::gather(., key = "distmetric", value = "distcat", 7:8) %>%
  dplyr::mutate(distcat = factor(distcat, levels = c("gcdistance_cat", "roaddistance_cat"), labels = c("GC Dist.", "Road Dist."))) %>%
  ggplot() +
  geom_boxplot(aes(x=distcat, y = malecotf)) +
  facet_wrap(.~distmetric) +
  theme_ibd +
  theme(axis.text.x = element_text(angle = 90))






```
