### Permutation Test for Within Cluster

```{r}
nsmpls <- nrow(mtdt)
hv001clsts <- unique(mtdt$hv001)

# do we draw the same or a different cluster if we draw 
reps <- 1e4
ret <- sapply(1:reps, function(x){
  ret <- sample(1:length(hv001clsts), size = 86, 
                prob = rep(1/length(hv001clsts), length(hv001clsts)),
                replace = T)
  return(mean(duplicated(ret)))
})

iters <- data.frame(iter = 1:length(ret),
                    prop = ret) 

# housekeeping for text below
true_count_meiotic_wthnclst <- ibD.meiotic.network %>% 
  tidygraph::activate(., "edges") %>% 
  dplyr::filter(hv001.x == hv001.y) %>% 
  tibble::as_tibble(.) %>% 
  nrow(.) %>% as.numeric(.)

perms.clstwthn.plotObj <- ggplot() +
  geom_bar(data = iters, aes(x = prop, y = ..count..), color = "#969696") +
  geom_vline(xintercept = true_count_meiotic_wthnclst, color = "#cb181d") +
  ggtitle("Permuted Within Cluster Pairs Expected to be at least Meiotic Sibs") +
  xlab("Meiotic Sib within Cluster Count") + ylab("Sim Count") +
  plot_theme

plot(perms.clstwthn.plotObj)




```

<!-- ### Permutation Test for Between Cluster -->

<!-- ```{r} -->
<!-- perms.clstbtwen <- perms %>%  -->
<!--   dplyr::filter(name == "clstwthn") %>%  -->
<!--   dplyr::select("results")  -->

<!-- # lift over result -->
<!-- perms.clstbtwen$wthncount <- purrr::map(perms.clstbtwen$results, function(x){ -->
<!--   return(sum(x != 0)) # if it was the same cluster, hv001 - hv001 would be 0  -->
<!-- }) -->

<!-- perms.clstbtwen <- perms.clstbtwen %>%  -->
<!--   tidyr::unnest(cols = "wthncount") -->


<!-- ``` -->

<!-- ```{r, results='asis'} -->

<!-- # housekeeping for text below -->
<!-- true_count_meiotic_btwnclst <- ibD.meiotic.network %>%  -->
<!--   tidygraph::activate(., "edges") %>%  -->
<!--   dplyr::filter(hv001.x != hv001.y) %>%  -->
<!--   tibble::as_tibble(.) %>%  -->
<!--   nrow(.) %>% as.numeric(.) -->


<!-- # geom density gets stretched out the curve density so need to set xlim -->
<!-- summary(perms.clstbtwen$wthncount) -->
<!-- true_count_meiotic_btwnclst -->
<!-- # so need to add 4 to each side to get exact min, will add 5 for balance -->

<!-- # get base plot -->
<!-- btwnclst.plotObj <- ggplot() + -->
<!--   geom_density(data = perms.clstbtwen, aes(x = wthncount), color = "#969696", fill = "#969696") + -->
<!--   xlim(42, 71) -->

<!-- # get ggplot data -->
<!-- perms.clst.pval <- quantile(perms.clstbtwen$wthncount, probs = c(0.025, 0.975)) -->
<!-- # extract ggplot data -->
<!-- ggplotdat <- ggplot2::ggplot_build(btwnclst.plotObj)$data[[1]] -->

<!-- # now get areas -->
<!-- perms.clst.lowertail <- ggplotdat %>%  -->
<!--   dplyr::filter(x <= perms.clst.pval[[1]]) -->
<!-- perms.clst.uppertail <- ggplotdat %>%  -->
<!--   dplyr::filter(x >= perms.clst.pval[[2]]) -->

<!-- # make final plot -->
<!-- btwnclst.plotObj <- btwnclst.plotObj + -->
<!--   geom_area(data = perms.clst.lowertail, aes(x = x, y = y), fill = "#4292c6", color = "#4292c6") + -->
<!--   geom_area(data = perms.clst.uppertail, aes(x = x, y = y), fill = "#4292c6", color = "#4292c6") + -->
<!--   geom_vline(xintercept = true_count_meiotic_btwnclst, color = "#cb181d") + -->
<!--   ggtitle("Permuted Between Cluster Pairs Expected to be at least Meiotic Sibs") + -->
<!--   xlab("Meiotic Sib Between Cluster Count") + ylab("Sim Proportion") + -->
<!--   plot_theme -->

<!-- plot(btwnclst.plotObj) -->

<!-- ``` -->


Overall, we detected `r nrow(ibD.meiotic)` pairs of samples that had at least meiotic similarity. Of these, `r paste(true_count_meiotic_wthnclst)` were within the same clusters, while `r nrow(notsameclst.edges)` were between clusters.   
**This tells us what we already know**. 

```{r}
ibD.meiotic.network.edges <- ibD.meiotic.network %>% 
  tidygraph::activate(., "edges") %>% 
  tibble::as_tibble(.)

```
